server {
    listen 80;
    server_name www.hacklabh.xyz;
    return 301 https://www.hacklabh.xyz$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.hacklabh.xyz;

    ssl_certificate /etc/letsencrypt/live/www.hacklabh.xyz/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.hacklabh.xyz/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/hacklabh-main;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}