name: Deploy to Raspberry PI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to RPi via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          password: ${{ secrets.PI_PASSWORD }}
          port: 22
          script: |
            cd /home/elvisds/BOT_HackLabH
            git pull origin main
            npm install
            pm2 restart BOT_HackLabH || pm2 start index.js --name BOT_HackLabH
